services:
  symfony-project:
    container_name: symfony
    image: docker-symfony 
    environment:
      - PROJECT_NAME=my_project
    networks:
      - symfony-project
    ports:
      - 8080:8000
    restart: unless-stopped
    volumes:
      - ./:/var/www

networks:
  symfony-project:
    name: symfony-project
